apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    app: myapp-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-app
  template:
    metadata:
      labels:
        app: myapp-app
    spec:
      containers:
      - name: loksai-eta-container
        image: loksaieta/myapp
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-np-service
  labels:
    app: myapp-app
spec:
  selector:
    app: myapp-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8081
    targetPort: 8081
